force-app/main/default/objects/Visa_Thought__c/Visa_Thought__c.object-meta.xml
<CustomObject>
    <description>info from Web form</description>
    <label>Visa Thought</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Numb</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visa Thoughts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visa_Thought__c/fields/Born2Invest_Offers__c.field-meta.xml
<CustomField>
    <fullName>Born2Invest_Offers__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Born2Invest Offers</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Visa_Thought__c/fields/degree_qualification__c.field-meta.xml
<CustomField>
    <fullName>degree_qualification__c</fullName>
    <label>Do you have a degree/qualification?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Doctorate</fullName>
            </value>
            <value>
                <fullName>Masters</fullName>
            </value>
            <value>
                <fullName>Bachelors</fullName>
            </value>
            <value>
                <fullName>High school</fullName>
            </value>
            <value>
                <fullName>Technical qualifications</fullName>
            </value>
            <value>
                <fullName>No qualifications</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visa_Thought__c/fields/Do_you_own_a_business__c.field-meta.xml
<CustomField>
    <fullName>Do_you_own_a_business__c</fullName>
    <label>Do you own a business?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visa_Thought__c/fields/Full_name__c.field-meta.xml
<CustomField>
    <fullName>Full_name__c</fullName>
    <label>Full name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visa_Thought__c/fields/How_much_can_you_invest__c.field-meta.xml
<CustomField>
    <fullName>How_much_can_you_invest__c</fullName>
    <label>How much can you invest</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nothing</fullName>
            </value>
            <value>
                <fullName>5,000 - 20,000</fullName>
            </value>
            <value>
                <fullName>21,000 - 50,000</fullName>
            </value>
            <value>
                <fullName>51,000 - 100,000</fullName>
            </value>
            <value>
                <fullName>100,000 - 500,000</fullName>
            </value>
            <value>
                <fullName>500,000 +</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visa_Thought__c/fields/Money_available__c.field-meta.xml
<CustomField>
    <fullName>Money_available__c</fullName>
    <label>Money available within the next 30 days</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visa_Thought__c/fields/When_would_you_like_to_move__c.field-meta.xml
<CustomField>
    <fullName>When_would_you_like_to_move__c</fullName>
    <label>When would you like to move?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1-3 months</fullName>
            </value>
            <value>
                <fullName>4-6 months</fullName>
            </value>
            <value>
                <fullName>6+ months</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visa_Thought__c/fields/Where_would_you_like_to_move__c.field-meta.xml
<CustomField>
    <fullName>Where_would_you_like_to_move__c</fullName>
    <label>Where would you like to move</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Europe/UK</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>South America</fullName>
            </value>
            <value>
                <fullName>Middle East</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visa_Thought__c/fields/Who_is_coming_with_you__c.field-meta.xml
<CustomField>
    <fullName>Who_is_coming_with_you__c</fullName>
    <label>Who is coming with you?</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Spouse</fullName>
            </value>
            <value>
                <fullName>Parents</fullName>
            </value>
            <value>
                <fullName>Children</fullName>
            </value>
            <value>
                <fullName>Grandparents</fullName>
            </value>
            <value>
                <fullName>Other dependants</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visa_Thought__c/fields/Why_do_you_want_to_move__c.field-meta.xml
<CustomField>
    <fullName>Why_do_you_want_to_move__c</fullName>
    <label>Why do you want to move?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tax reasons</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Business reasons</fullName>
            </value>
            <value>
                <fullName>To find a job</fullName>
            </value>
            <value>
                <fullName>Asylum</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/newVisaControllerTest.cls
@isTest
public class newVisaControllerTest {
    
    @isTest 
    private static void testController(){
        
        newVisaController controller = new newVisaController();
        
        Test.setMock(HttpCalloutMock.class, new CalloutWPMock()); 
        
        Visa_Thought__c visa = controller.getVisa();
        
        controller.step1();
        controller.step2();
        //controller.freezePageSend();
        
        visa.Email__c = 'test@mail.com';
        visa.Born2Invest_Offers__c = true;
        visa.Full_name__c = '1111';
        visa.Telephone_number__c = 'test';
        visa.Nationality__c = 'China';
        
        controller.step2();
        
        visa.Full_name__c = 'Test Person';
        visa.Telephone_number__c = '11111111';
        
        controller.step2();
        controller.step3();
        
        visa.degree_qualification__c = 'Doctorate';
        visa.Who_is_coming_with_you__c = 'Parents';
        visa.Do_you_own_a_business__c = 'No';
        visa.How_much_can_you_invest__c = '51,000 - 100,000';
        visa.Money_available__c = 'Yes';
        
        controller.step3();
        controller.save();
        
        visa.Where_would_you_like_to_move__c = 'South America';
        visa.Why_do_you_want_to_move__c = 'Education';
        visa.When_would_you_like_to_move__c = '4-6 months';
        visa.LinkedIn__c = 'My linkedIn';
        
        controller.browserurl = 'site.com';

        controller.save();
    }
}