force-app/main/default/objects/Visa_Thought__c/Visa_Thought__c.object-meta.xml
<CustomObject>
    <description>info from Web form</description>
    <label>Visa Thought</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Numb</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visa Thoughts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visa_Thought__c/fields/Born2Invest_Offers__c.field-meta.xml
<CustomField>
    <fullName>Born2Invest_Offers__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Born2Invest Offers</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Visa_Thought__c/fields/degree_qualification__c.field-meta.xml
<CustomField>
    <fullName>degree_qualification__c</fullName>
    <label>Do you have a degree/qualification?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Doctorate</fullName>
            </value>
            <value>
                <fullName>Masters</fullName>
            </value>
            <value>
                <fullName>Bachelors</fullName>
            </value>
            <value>
                <fullName>High school</fullName>
            </value>
            <value>
                <fullName>Technical qualifications</fullName>
            </value>
            <value>
                <fullName>No qualifications</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visa_Thought__c/fields/Do_you_own_a_business__c.field-meta.xml
<CustomField>
    <fullName>Do_you_own_a_business__c</fullName>
    <label>Do you own a business?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visa_Thought__c/fields/Full_name__c.field-meta.xml
<CustomField>
    <fullName>Full_name__c</fullName>
    <label>Full name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visa_Thought__c/fields/How_much_can_you_invest__c.field-meta.xml
<CustomField>
    <fullName>How_much_can_you_invest__c</fullName>
    <label>How much can you invest</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nothing</fullName>
            </value>
            <value>
                <fullName>5,000 - 20,000</fullName>
            </value>
            <value>
                <fullName>21,000 - 50,000</fullName>
            </value>
            <value>
                <fullName>51,000 - 100,000</fullName>
            </value>
            <value>
                <fullName>100,000 - 500,000</fullName>
            </value>
            <value>
                <fullName>500,000 +</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visa_Thought__c/fields/Money_available__c.field-meta.xml
<CustomField>
    <fullName>Money_available__c</fullName>
    <label>Money available within the next 30 days</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visa_Thought__c/fields/Source_URL__c.field-meta.xml
<CustomField>
    <fullName>Source_URL__c</fullName>
    <label>Source URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visa_Thought__c/fields/When_would_you_like_to_move__c.field-meta.xml
<CustomField>
    <fullName>When_would_you_like_to_move__c</fullName>
    <label>When would you like to move?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1-3 months</fullName>
            </value>
            <value>
                <fullName>4-6 months</fullName>
            </value>
            <value>
                <fullName>6+ months</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visa_Thought__c/fields/Where_would_you_like_to_move__c.field-meta.xml
<CustomField>
    <fullName>Where_would_you_like_to_move__c</fullName>
    <label>Where would you like to move</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Europe/UK</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>South America</fullName>
            </value>
            <value>
                <fullName>Middle East</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visa_Thought__c/fields/Who_is_coming_with_you__c.field-meta.xml
<CustomField>
    <fullName>Who_is_coming_with_you__c</fullName>
    <label>Who is coming with you?</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Spouse</fullName>
            </value>
            <value>
                <fullName>Parents</fullName>
            </value>
            <value>
                <fullName>Children</fullName>
            </value>
            <value>
                <fullName>Grandparents</fullName>
            </value>
            <value>
                <fullName>Other dependants</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visa_Thought__c/fields/Why_do_you_want_to_move__c.field-meta.xml
<CustomField>
    <fullName>Why_do_you_want_to_move__c</fullName>
    <label>Why do you want to move?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tax reasons</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Business reasons</fullName>
            </value>
            <value>
                <fullName>To find a job</fullName>
            </value>
            <value>
                <fullName>Asylum</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/newVisaController.cls
public class newVisaController {
    
    public static final String ADD_VALUE = 'Please, enter a value.';
    public static final String SELECT_VALUE = 'Please, select a value.';
    public static final String TICK_VALUE = 'Please, tick a checkbox.';
    public static final String ONLY_LETTERS = 'Please, enter only letters.';
    public static final String ONLY_PHONE = 'Please, enter valid phone number.';
    
    //public static final String FREEZE = 'FREEZE';
    //public static final String UNFREEZE = 'UNFREEZE';
    //public Boolean freezed = false;
    
    public Visa_Thought__c visa;
    public String browserurl 	{get;set;}
    
    public Visa_Thought__c getVisa() {
        if(visa == null) visa = new Visa_Thought__c();
        return visa;
    }
    
    public PageReference step1() {
        return Page.VisaStep1;
    }
    
    public PageReference step2() {
        
        Boolean hasError = false;
        
        if(visa.Email__c == null) {
            visa.Email__c.addError(ADD_VALUE);
            hasError = true;
        }
        
        if(visa.Born2Invest_Offers__c == false) {
            visa.Born2Invest_Offers__c.addError(TICK_VALUE);
            hasError = true;
        }
        
        if(visa.Full_name__c == null) {
            visa.Full_name__c.addError(ADD_VALUE);
            hasError = true;
        }
        else if( !visa.Full_name__c.isAlphaSpace()) {
            visa.Full_name__c.addError(ONLY_LETTERS);
            hasError = true;
        }
        
        if(visa.Telephone_number__c == null){
            visa.Telephone_number__c.addError(ADD_VALUE);
            hasError = true;
        }
        else if( !Pattern.matches('[0-9(),./\\+-]+', visa.Telephone_number__c)) {
            visa.Telephone_number__c.addError(ONLY_PHONE);
            hasError = true;
        }
        
         if(visa.Nationality__c == null){
            visa.Nationality__c.addError(SELECT_VALUE);
            hasError = true;
        }
        
        if (hasError) return Page.VisaStep1;
        return Page.VisaStep2;
    }
    
    public PageReference step3() {
        Boolean hasError = false;
        
        if(visa.degree_qualification__c == null) {
            visa.degree_qualification__c.addError(SELECT_VALUE);
            hasError = true;
        }
        
        if(visa.Who_is_coming_with_you__c == null) {
            visa.Who_is_coming_with_you__c.addError(SELECT_VALUE);
            hasError = true;
        }
        
        if(visa.Do_you_own_a_business__c == null) {
            visa.Do_you_own_a_business__c.addError(SELECT_VALUE);
            hasError = true;
        }
        
        if(visa.How_much_can_you_invest__c == null) {
            visa.How_much_can_you_invest__c.addError(SELECT_VALUE);
            hasError = true;
        }
        
        if(visa.Money_available__c == null) {
            visa.Money_available__c.addError(SELECT_VALUE);
            hasError = true;
        }
        
        if (hasError) return Page.VisaStep2;
        return Page.VisaStep3;
    }
    
    public PageReference save() { 
        Boolean hasError = false;
        
        if(visa.Where_would_you_like_to_move__c == null) {
            visa.Where_would_you_like_to_move__c.addError(SELECT_VALUE);
            hasError = true;
        }
        
        if(visa.Why_do_you_want_to_move__c == null) {
            visa.Why_do_you_want_to_move__c.addError(SELECT_VALUE);
            hasError = true;
        } 
        
        if(visa.When_would_you_like_to_move__c == null) {
            visa.When_would_you_like_to_move__c.addError(SELECT_VALUE);
            hasError = true;
        }
        
         if(visa.LinkedIn__c == null) {
            visa.LinkedIn__c.addError(ADD_VALUE);
            hasError = true;
        }
        
        
        if (hasError) return Page.VisaStep3;
        
        
        System.debug('browserurl: '+ browserurl);
        
        visa.Source_URL__c = browserurl.left(255);
        insert visa;
        
        //unfreezePageSend();
        
        return Page.visaStep4;
    }
    
    /*
    public void freezePageSend(){
        if(!freezed) {
            freezed = true;
            CalloutWP.makeCallout(FREEZE, browserurl);
            system.debug('sent to freeze: ' + browserurl);
        }    
    }
    
    public void unfreezePageSend(){
        if(freezed) {
            freezed = false;
            CalloutWP.makeCallout(UNFREEZE, browserurl);
            system.debug('sent to unfreeze: ' + browserurl);
        }    
    }
*/
    
}